/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Email = IDL.Text;

export const idlService = IDL.Service({
  'getTotalWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserPosition' : IDL.Func([Email], [IDL.Nat], ['query']),
  'submitEmail' : IDL.Func([Email], [IDL.Nat], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Email = IDL.Text;
  
  return IDL.Service({
    'getTotalWaitlistCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserPosition' : IDL.Func([Email], [IDL.Nat], ['query']),
    'submitEmail' : IDL.Func([Email], [IDL.Nat], []),
  });
};

export const init = ({ IDL }) => { return []; };